// Module registry error codes
// @see PLAN.md §2.7 — Module registry boot validation

export const MODULE_NOT_FOUND = 'MODULE_NOT_FOUND';
export const MODULE_ALREADY_ENABLED = 'MODULE_ALREADY_ENABLED';
export const MODULE_DEPENDENCY_MISSING = 'MODULE_DEPENDENCY_MISSING';
export const MODULE_DEPENDENCY_NOT_ENTITLED = 'MODULE_DEPENDENCY_NOT_ENTITLED';
export const MODULE_HAS_DEPENDENTS = 'MODULE_HAS_DEPENDENTS';
export const MODULE_DUPLICATE_KEY = 'MODULE_DUPLICATE_KEY';
export const MODULE_DUPLICATE_PERMISSION = 'MODULE_DUPLICATE_PERMISSION';
export const MODULE_DUPLICATE_EVENT = 'MODULE_DUPLICATE_EVENT';
export const MODULE_DUPLICATE_TABLE_PREFIX = 'MODULE_DUPLICATE_TABLE_PREFIX';
export const MODULE_DUPLICATE_PORT = 'MODULE_DUPLICATE_PORT';
export const MODULE_CONSUMED_EVENT_MISSING = 'MODULE_CONSUMED_EVENT_MISSING';
export const MODULE_CONSUMED_PORT_MISSING = 'MODULE_CONSUMED_PORT_MISSING';
export const MODULE_BOOT_VALIDATION_FAILED = 'MODULE_BOOT_VALIDATION_FAILED';
