export {
  MODULE_NOT_FOUND,
  MODULE_ALREADY_ENABLED,
  MODULE_DEPENDENCY_MISSING,
  MODULE_DEPENDENCY_NOT_ENTITLED,
  MODULE_HAS_DEPENDENTS,
  MODULE_DUPLICATE_PERMISSION,
  MODULE_DUPLICATE_EVENT,
  MODULE_DUPLICATE_TABLE_PREFIX,
  MODULE_DUPLICATE_PORT,
  MODULE_CONSUMED_PORT_MISSING,
  MODULE_BOOT_VALIDATION_FAILED,
} from './errors.js';
