packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'
allowBuilds:
  '@nestjs/core': true
  argon2: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
