import type { Metadata, Viewport } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { getLocale } from 'next-intl/server';

import { SwRegister } from '@/components/pwa/sw-register';
import './globals.css';

const inter = Inter({
  subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'],
  variable: '--font-inter',
  display: 'swap',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'ModuBiz',
    template: '%s | ModuBiz',
  },
  description: 'Multi-tenant modular business management platform',
  // PWA shell (Phase 6.7): brand icons + iOS standalone metadata. The web app
  // manifest is generated by app/manifest.ts and linked automatically.
  icons: {
    icon: '/icon.svg',
    apple: '/icons/apple-touch-icon.png',
  },
  appleWebApp: {
    capable: true,
    title: 'ModuBiz POS',
    statusBarStyle: 'default',
  },
};

/** Theme color matches the manifest so the installed app chrome blends with --primary. */
export const viewport: Viewport = {
  themeColor: '#0f1729',
};

/**
 * Root layout — sets up fonts and global HTML structure.
 * `lang` and `dir` are derived from the active locale so RTL locales
 * (e.g. Arabic) render correctly.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const dir = locale.startsWith('ar') ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir} className={`${inter.variable} ${jetbrainsMono.variable}`} suppressHydrationWarning>
      <body className="min-h-screen antialiased">
        {children}
        {/* Registers the offline shell (public/sw.js) — silent progressive enhancement. */}
        <SwRegister />
      </body>
    </html>
  );
}
