import type { Metadata, Viewport } from 'next';
import { IBM_Plex_Sans_Arabic, Inter, JetBrains_Mono } from 'next/font/google';
import { getLocale } from 'next-intl/server';

import { SwRegister } from '@/components/pwa/sw-register';
import './globals.css';

const inter = Inter({
  subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'],
  variable: '--font-inter',
  display: 'swap',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

// Arabic UI font (UI_UX_GUIDELINES §2.2): Inter has no Arabic glyphs, so the
// ar locale was falling back to system fonts. Only the arabic subset is
// loaded — Latin text and Western-Arabic numerals keep rendering in Inter via
// per-character font fallback (RTL §8.3).
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ['arabic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-arabic',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'ModuBiz',
    template: '%s | ModuBiz',
  },
  description: 'Multi-tenant modular business management platform',
  // PWA shell (Phase 6.7): brand icons + iOS standalone metadata. The web app
  // manifest is generated by app/manifest.ts and linked automatically.
  icons: {
    icon: '/icon.svg',
    apple: '/icons/apple-touch-icon.png',
  },
  appleWebApp: {
    capable: true,
    title: 'ModuBiz POS',
    statusBarStyle: 'default',
  },
};

/** Theme color matches the manifest so the installed app chrome blends with --primary. */
export const viewport: Viewport = {
  themeColor: '#0f1729',
};

/**
 * Root layout — sets up fonts and global HTML structure.
 * `lang` and `dir` are derived from the active locale so RTL locales
 * (e.g. Arabic) render correctly.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const dir = locale.startsWith('ar') ? 'rtl' : 'ltr';

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${inter.variable} ${jetbrainsMono.variable} ${ibmPlexSansArabic.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Apply the persisted theme (light/dark/system) BEFORE first paint so
            a dark-mode user never sees a flash of light mode on reload. The
            topbar toggle writes `modubiz.theme` to localStorage — keep this
            script in sync with src/lib/theme.ts. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=window.localStorage.getItem('modubiz.theme');var d=t==='dark'||(t==='system'&&window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches);if(d)document.documentElement.classList.add('dark');}catch(e){}})();`,
          }}
        />
      </head>
      <body className="min-h-screen antialiased">
        {children}
        {/* Registers the offline shell (public/sw.js) — silent progressive enhancement. */}
        <SwRegister />
      </body>
    </html>
  );
}
