export { Role, RoleError, SYSTEM_ROLES, PLATFORM_PERMISSIONS, SYSTEM_ROLE_PERMISSIONS, type SystemRoleKey, type RoleData, type RolePermissionData } from './role.entity.js';
export {
  ROLE_NOT_FOUND,
  SYSTEM_ROLE_IMMUTABLE,
  LAST_OWNER_ROLE,
  CANNOT_GRANT_UNOWNED_PERMISSION,
  CUSTOM_ROLE_PLATFORM_PERMISSION_DENIED,
  TRANSFER_TARGET_NOT_FOUND,
  CANNOT_TRANSFER_TO_SELF,
  NOMINATION_REQUIRED,
  PERMISSION_NOT_FOUND,
  ROLE_KEY_EXISTS,
} from './errors.js';
