export {
  defineModule,
  validateDescriptors,
  MODULE_KEYS,
  DESCRIPTOR_ERROR,
  MODULE_FEATURES,
  defaultFeaturesForModule,
  featuresForModule,
} from './module/index.js';
export type {
  ModuleDescriptor,
  ModuleKey,
  PermissionKey,
  EventName,
  NavigationItem,
  DashboardWidget,
  PortDeclaration,
  DescriptorValidationError,
  DescriptorErrorCode,
  ModuleFeature,
} from './module/index.js';

export { ALL_PERMISSIONS } from './permissions/index.js';
export type { Permission } from './permissions/index.js';

export {
  CRM_EVENTS,
  crmContactCreatedV1Schema,
  crmContactUpdatedV1Schema,
  crmDealStageChangedV1Schema,
  crmDealWonV1Schema,
  crmDealLostV1Schema,
  INVENTORY_EVENTS,
  STOCK_MOVEMENT_TYPES,
  inventoryProductCreatedV1Schema,
  inventoryProductArchivedV1Schema,
  inventoryProductRestoredV1Schema,
  inventoryStockLevelChangedV1Schema,
  inventoryStockDepletedV1Schema,
  inventoryReorderPointReachedV1Schema,
  inventoryStockMovementRecordedV1Schema,
  POS_EVENTS,
  posSaleCompletedV1Schema,
  posSaleRefundedV1Schema,
  posShiftOpenedV1Schema,
  posShiftClosedV1Schema,
  ACCOUNTING_EVENTS,
  accountingInvoiceIssuedV1Schema,
  accountingInvoicePaidV1Schema,
  accountingCreditNoteIssuedV1Schema,
  accountingJournalPostedV1Schema,
  accountingPaymentReceivedV1Schema,
  PURCHASING_EVENTS,
  purchasingBillApprovedV1Schema,
  purchasingPaymentRecordedV1Schema,
  purchasingSupplierReturnApprovedV1Schema,
  minorUnitsString,
  signedMinorUnitsString,
  currencyCode,
  decimalString,
  signedDecimalString,
} from './events/index.js';
export type {
  CrmContactCreatedV1,
  CrmContactUpdatedV1,
  CrmDealStageChangedV1,
  CrmDealWonV1,
  CrmDealLostV1,
  InventoryProductCreatedV1,
  InventoryProductArchivedV1,
  InventoryProductRestoredV1,
  InventoryStockLevelChangedV1,
  InventoryStockDepletedV1,
  InventoryReorderPointReachedV1,
  InventoryStockMovementRecordedV1,
  PosSaleCompletedV1,
  PosSaleRefundedV1,
  PosShiftOpenedV1,
  PosShiftClosedV1,
  AccountingInvoiceIssuedV1,
  AccountingInvoicePaidV1,
  AccountingCreditNoteIssuedV1,
  AccountingJournalPostedV1,
  AccountingPaymentReceivedV1,
  PurchasingBillApprovedV1,
  PurchasingPaymentRecordedV1,
  PurchasingSupplierReturnApprovedV1,
} from './events/index.js';

export type {
  TransactionRef,
  PortToken,
  SearchContributor,
  SearchResult,
  FxRateRead,
  AvailabilitySnapshot,
  ReserveStockInput,
  RestockInput,
  ReservationRef,
  InventoryStockPort,
  MovementEventCollector,
  MovementLineInput,
  ReceiveMovementInput,
  IssueMovementInput,
  SupplierReturnLineInput,
  ReturnToSupplierMovementInput,
  AdjustCostMovementInput,
  InventoryMovementPort,
} from './ports/index.js';
export {
  SEARCH_CONTRIBUTORS,
  MEMBERSHIP_READ_PORT,
  ORGANIZATION_READ_PORT,
  FX_RATE_READ_PORT,
  INVENTORY_STOCK_PORT,
  INVENTORY_MOVEMENT_PORT,
} from './ports/index.js';
export type { MembershipReadPort, OrganizationReadPort, FxRateReadPort } from './ports/index.js';
