/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/organizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['OrganizationsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['OrganizationsController_getById'];
    put?: never;
    post?: never;
    delete: operations['OrganizationsController_delete'];
    options?: never;
    head?: never;
    patch: operations['OrganizationsController_update'];
    trace?: never;
  };
  '/v1/organizations/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['OrganizationsController_getCurrent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{id}/cancel-deletion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['OrganizationsController_cancelDeletion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{id}/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['OrganizationsController_getSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['OrganizationsController_updateSettings'];
    trace?: never;
  };
  '/v1/users/me/organizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MembershipsController_listMyOrganizations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MembershipsController_listMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MembershipsController_listInvitations'];
    put?: never;
    post: operations['MembershipsController_invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/invitations/{id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MembershipsController_acceptInvitation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/memberships/{id}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['MembershipsController_updateRole'];
    trace?: never;
  };
  '/v1/memberships/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['MembershipsController_removeMember'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/invitations/{id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MembershipsController_revokeInvitation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/switch-org': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MembershipsController_switchOrg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/request-password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_requestPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/complete-password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_completePasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['UsersController_updateProfile'];
    trace?: never;
  };
  '/v1/users/me/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UsersController_changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_listSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['UsersController_revokeSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RolesController_listRoles'];
    put?: never;
    post: operations['RolesController_createRole'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/roles/matrix': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RolesController_getRoleMatrix'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/roles/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['RolesController_deleteRole'];
    options?: never;
    head?: never;
    patch: operations['RolesController_updateRole'];
    trace?: never;
  };
  '/v1/memberships/{id}/assign-role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RolesController_assignRole'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/transfer-ownership': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RolesController_transferOwnership'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/billing': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['BillingController_getBilling'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/billing/subscription': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BillingController_createSubscription'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/billing/trial': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BillingController_enableTrial'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/billing/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BillingController_disableModule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/billing/reconcile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BillingController_reconcile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/billing/webhook': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BillingController_handleWebhook'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/modules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ModuleRegistryController_listModules'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/navigation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ModuleRegistryController_getNavigation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/dashboard/widgets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ModuleRegistryController_getDashboardWidgets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/modules/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ModuleRegistryController_enableModule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/modules/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ModuleRegistryController_disableModule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/organizations/{orgId}/audit-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuditLogController_queryAuditLog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SearchController_search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/currencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FxRatesController_listCurrencies'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/fx-rates/{baseCurrency}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FxRatesController_getRatesForBase'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/fx-rates/{baseCurrency}/{quoteCurrency}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FxRatesController_getRate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/fx-rates/snapshot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FxRatesController_triggerSnapshot'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/contacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ContactsController_list'];
    put?: never;
    post: operations['ContactsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/contacts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ContactsController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ContactsController_update'];
    trace?: never;
  };
  '/v1/crm/contacts/merge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ContactsController_merge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/companies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_list'];
    put?: never;
    post: operations['CompaniesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/companies/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CompaniesController_update'];
    trace?: never;
  };
  '/v1/crm/deals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DealsController_list'];
    put?: never;
    post: operations['DealsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/deals/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DealsController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/deals/{id}/move-stage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DealsController_moveStage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/deals/{id}/close': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DealsController_close'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/deals/{id}/reopen': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DealsController_reopen'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActivitiesController_list'];
    put?: never;
    post: operations['ActivitiesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/activities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActivitiesController_getById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ActivitiesController_update'];
    trace?: never;
  };
  '/v1/crm/activities/{id}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ActivitiesController_complete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/pipelines/default': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['PipelinesController_getDefault'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/notes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NotesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/crm/notes/{relatedType}/{relatedId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['NotesController_listByRelated'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateOrganizationDto: {
      name: string;
      slug: string;
      countryCode: string;
      /** @default UTC */
      timezone: string;
      baseCurrency: string;
      /** @default en */
      defaultLocale: string;
    };
    OrganizationEnvelopeResponse: {
      data: {
        id: string;
        name: string;
        slug: string;
        countryCode: string;
        timezone: string;
        baseCurrency: string;
        defaultLocale: string;
        status: string;
        deletionScheduledAt: string | null;
        createdAt: string;
        updatedAt: string;
      };
    };
    OrganizationDetailResponse: {
      data: {
        id: string;
        name: string;
        slug: string;
        countryCode: string;
        timezone: string;
        baseCurrency: string;
        defaultLocale: string;
        status: string;
        deletionScheduledAt: string | null;
        createdAt: string;
        updatedAt: string;
      };
      settings: {
        id: string;
        organizationId: string;
        locale: string;
        timezone: string;
        baseCurrency: string;
        numberPreferences: {
          [key: string]: unknown;
        };
        datePreferences: {
          [key: string]: unknown;
        };
        receiptFooter: string | null;
        createdAt: string;
        updatedAt: string;
      } | null;
    };
    UpdateOrganizationDto: {
      name?: string;
      countryCode?: string;
      timezone?: string;
      baseCurrency?: string;
      defaultLocale?: string;
      hasMonetaryRecords?: boolean;
    };
    OrganizationDeleteResponse: {
      data: {
        deletionScheduledAt: string;
        message: string;
      };
    };
    SettingsEnvelopeResponse: {
      data: {
        id: string;
        organizationId: string;
        locale: string;
        timezone: string;
        baseCurrency: string;
        numberPreferences: {
          [key: string]: unknown;
        };
        datePreferences: {
          [key: string]: unknown;
        };
        receiptFooter: string | null;
        createdAt: string;
        updatedAt: string;
      } | null;
    };
    UpdateOrganizationSettingsDto: {
      locale?: string;
      timezone?: string;
      baseCurrency?: string;
      numberPreferences?: {
        [key: string]: unknown;
      };
      datePreferences?: {
        [key: string]: unknown;
      };
      receiptFooter?: string | null;
    };
    SettingsUpdateEnvelopeResponse: {
      data: {
        id: string;
        organizationId: string;
        locale: string;
        timezone: string;
        baseCurrency: string;
        numberPreferences: {
          [key: string]: unknown;
        };
        datePreferences: {
          [key: string]: unknown;
        };
        receiptFooter: string | null;
        createdAt: string;
        updatedAt: string;
      };
    };
    MyOrganizationsEnvelopeResponse: {
      data: {
        organizationId: string;
        organizationName: string;
        organizationSlug: string;
        roleId: string;
        status: string;
        organizationStatus: string;
        joinedAt: string;
        current: boolean;
      }[];
    };
    MembersEnvelopeResponse: {
      data: {
        id: string;
        userId: string;
        email: string;
        name: string;
        roleId: string;
        status: string;
        joinedAt: string;
      }[];
    };
    InvitationsEnvelopeResponse: {
      data: {
        id: string;
        name: string | null;
        email: string;
        roleId: string;
        status: string;
        expiresAt: string;
        createdAt: string;
      }[];
    };
    InviteUserDto: {
      name: string;
      /** Format: email */
      email: string;
      /** Format: uuid */
      roleId: string;
    };
    InvitationCreatedEnvelopeResponse: {
      data: {
        invitationId: string;
      };
    };
    MembershipMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    UpdateMemberRoleDto: {
      /** Format: uuid */
      roleId: string;
    };
    SwitchOrgDto: {
      /** Format: uuid */
      organizationId: string;
    };
    SwitchOrgEnvelopeResponse: {
      data: {
        accessToken: string;
        refreshToken: string;
      };
    };
    SignupDto: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
      preferredLocale?: string;
    };
    AuthMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
      device?: string;
    };
    AuthEnvelopeResponse: {
      data: {
        accessToken: string;
        refreshToken: string;
        user: {
          id: string;
          email: string;
          name: string;
          preferredLocale: string | null;
          emailVerified: boolean;
        };
      };
    };
    RefreshTokenDto: {
      refreshToken: string;
    };
    TokenPairEnvelopeResponse: {
      data: {
        accessToken: string;
        refreshToken: string;
      };
    };
    RequestPasswordResetDto: {
      /** Format: email */
      email: string;
    };
    CompletePasswordResetDto: {
      /** Format: email */
      email: string;
      resetToken: string;
      newPassword: string;
    };
    ProfileEnvelopeResponse: {
      data: {
        id: string;
        email: string;
        name: string;
        preferredLocale: string | null;
        emailVerified: boolean;
        createdAt: string;
      };
    };
    UpdateProfileDto: {
      name?: string;
      preferredLocale?: string | null;
    };
    PasswordChangeDto: {
      currentPassword: string;
      newPassword: string;
    };
    UserMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    SessionsEnvelopeResponse: {
      data: {
        id: string;
        device?: string;
        ip?: string;
        createdAt: string;
        expiresAt: string;
        current: boolean;
      }[];
    };
    RolesEnvelopeResponse: {
      data: {
        id: string;
        key: string;
        nameI18n: {
          [key: string]: string;
        };
        description: string | null;
        isSystem: boolean;
        permissions: string[];
        memberCount: number;
      }[];
    };
    RoleMatrixEnvelopeResponse: {
      data: {
        systemRoles: {
          key: string;
          permissions: string[];
        }[];
        customRoles: {
          id: string;
          key: string;
          nameI18n: {
            [key: string]: string;
          };
          description: string | null;
          permissions: string[];
        }[];
        platformPermissions: string[];
        permissionCatalog: string[];
      };
    };
    CreateRoleDto: {
      key: string;
      /** @default {} */
      nameI18n: {
        [key: string]: string;
      };
      description?: string;
      permissionKeys?: string[];
    };
    RoleCreatedEnvelopeResponse: {
      data: {
        id: string;
      };
    };
    UpdateRoleDto: {
      nameI18n?: {
        [key: string]: string;
      };
      description?: string | null;
      permissionKeys?: string[];
    };
    RoleMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    AssignRoleDto: {
      /** Format: uuid */
      roleId: string;
    };
    TransferOwnershipDto: {
      /** Format: uuid */
      targetUserId: string;
    };
    BillingEnvelopeResponse: {
      data: {
        subscription: {
          id: string;
          stripeCustomerId: string;
          status: string;
          billingCurrency: string;
          currentPeriodEnd: string | null;
        } | null;
        entitlements: {
          moduleKey: string;
          state: string;
          trialEndsAt: string | null;
          activatedAt: string | null;
        }[];
      };
    };
    CreateSubscriptionDto: {
      organizationName: string;
      /** Format: email */
      email: string;
      billingCurrency: string;
      /** @default [] */
      priceKeys: string[];
    };
    SubscriptionCreatedEnvelopeResponse: {
      data: {
        subscriptionId: string;
      };
    };
    EnableModuleTrialDto: {
      moduleKey: string;
      /** @default false */
      skipTrial: boolean;
    };
    BillingMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    BillingDisableModuleDto: {
      moduleKey: string;
    };
    ReconcileEnvelopeResponse: {
      data: {
        updated: number;
        alerts: string[];
      };
    };
    WebhookResponse: {
      received: boolean;
    };
    ModuleCatalogEnvelopeResponse: {
      data: {
        key: string;
        nameKey: string;
        descriptionKey: string | null;
        icon: string | null;
        dependsOn: string[];
        trialDays: number;
      }[];
    };
    NavigationEnvelopeResponse: {
      data: {
        moduleKey: string;
        labelKey: string;
        icon?: string;
        items: {
          labelKey: string;
          href: string;
          icon?: string;
          children?: {
            labelKey: string;
            href: string;
            icon?: string;
          }[];
        }[];
      }[];
    };
    DashboardWidgetsEnvelopeResponse: {
      data: {
        moduleKey: string;
        labelKey: string;
        widgets: {
          id: string;
          titleKey: string;
          width: number;
          height: number;
          icon?: string;
        }[];
      }[];
    };
    EnableModuleDto: {
      moduleKey: string;
    };
    ModuleRegistryMessageEnvelopeResponse: {
      data: {
        message: string;
      };
    };
    DisableModuleDto: {
      moduleKey: string;
    };
    AuditLogQueryEnvelopeResponse: {
      data: {
        entries: {
          id: string;
          actorUserId: string | null;
          actorType: string;
          action: string;
          entityType: string;
          entityId: string;
          before: {
            [key: string]: unknown;
          } | null;
          after: {
            [key: string]: unknown;
          } | null;
          ip: string | null;
          correlationId: string | null;
          occurredAt: string;
        }[];
        total: number;
        page: number;
        pageSize: number;
      };
    };
    SearchEnvelopeResponse: {
      data: {
        query: string;
        results: {
          moduleKey: string;
          labelKey: string;
          results: {
            id: string;
            title: string;
            description?: string;
            href: string;
            icon?: string;
          }[];
        }[];
      };
    };
    CurrenciesEnvelopeResponse: {
      data: {
        code: string;
        exponent: number;
        symbol: string;
        name: string;
      }[];
    };
    FxRatesEnvelopeResponse: {
      data: {
        baseCurrency: string;
        rates: {
          quoteCurrency: string;
          rate: string;
          validOn: string;
        }[];
      };
    };
    FxRateEnvelopeResponse: {
      data: {
        baseCurrency: string;
        quoteCurrency: string;
        rate: string;
        validOn: string;
        source: string;
      };
    };
    FxSnapshotEnvelopeResponse: {
      data: {
        pairsStored: number;
        source: string;
      };
    };
    ContactListEnvelopeResponse: {
      data: {
        items: {
          id: string;
          firstName: string;
          lastName: string;
          email: string | null;
          phone: string | null;
          secondaryPhone: string | null;
          companyId: string | null;
          ownerUserId: string | null;
          preferredLocale: string | null;
          preferredCurrency: string | null;
          createdByUserId?: string | null;
          updatedByUserId?: string | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
      };
    };
    ContactEnvelopeResponse: {
      data: {
        id: string;
        firstName: string;
        lastName: string;
        email: string | null;
        phone: string | null;
        secondaryPhone: string | null;
        companyId: string | null;
        ownerUserId: string | null;
        preferredLocale: string | null;
        preferredCurrency: string | null;
        createdByUserId?: string | null;
        updatedByUserId?: string | null;
      };
    };
    CreateContactDto: {
      firstName: string;
      lastName: string;
      /** Format: email */
      email?: string | null;
      phone?: string | null;
      secondaryPhone?: string | null;
      /** Format: uuid */
      companyId?: string | null;
      /** Format: uuid */
      ownerUserId?: string | null;
      preferredLocale?: string | null;
      preferredCurrency?: string | null;
    };
    UpdateContactDto: {
      firstName?: string;
      lastName?: string;
      /** Format: email */
      email?: string | null;
      phone?: string | null;
      secondaryPhone?: string | null;
      /** Format: uuid */
      companyId?: string | null;
      /** Format: uuid */
      ownerUserId?: string | null;
      preferredLocale?: string | null;
      preferredCurrency?: string | null;
    };
    MergeContactsDto: {
      /** Format: uuid */
      sourceContactId: string;
      /** Format: uuid */
      targetContactId: string;
    };
    MergeEnvelopeResponse: {
      data: {
        id: string;
        firstName: string;
        lastName: string;
        email: string | null;
        phone: string | null;
        secondaryPhone: string | null;
        companyId: string | null;
        ownerUserId: string | null;
        preferredLocale: string | null;
        preferredCurrency: string | null;
        createdByUserId?: string | null;
        updatedByUserId?: string | null;
      };
    };
    CompanyListEnvelopeResponse: {
      data: {
        items: {
          id: string;
          name: string;
          domain: string | null;
          industry: string | null;
          address: {
            [key: string]: unknown;
          };
          ownerUserId: string | null;
          createdByUserId?: string | null;
          updatedByUserId?: string | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
      };
    };
    CompanyEnvelopeResponse: {
      data: {
        id: string;
        name: string;
        domain: string | null;
        industry: string | null;
        address: {
          [key: string]: unknown;
        };
        ownerUserId: string | null;
        createdByUserId?: string | null;
        updatedByUserId?: string | null;
      };
    };
    CreateCompanyDto: {
      name: string;
      domain?: string | null;
      industry?: string | null;
      /** @default {} */
      address: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      ownerUserId?: string | null;
    };
    UpdateCompanyDto: {
      name?: string;
      domain?: string | null;
      industry?: string | null;
      /** @default {} */
      address: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      ownerUserId?: string | null;
    };
    DealListEnvelopeResponse: {
      data: {
        items: {
          id: string;
          title: string;
          pipelineId: string;
          stageId: string;
          contactId: string | null;
          companyId: string | null;
          contactName?: string | null;
          companyName?: string | null;
          value: {
            amountMinor: string;
            currency: string;
          };
          exchangeRate: number | null;
          baseAmountMinor: string | null;
          /** @enum {string} */
          status: 'open' | 'won' | 'lost';
          closedAt: string | null;
          expectedCloseDate: string | null;
          ownerUserId: string | null;
          createdByUserId?: string | null;
          updatedByUserId?: string | null;
          createdAt?: string | null;
          updatedAt?: string | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalValueBaseMinor: string;
      };
    };
    DealEnvelopeResponse: {
      data: {
        id: string;
        title: string;
        pipelineId: string;
        stageId: string;
        contactId: string | null;
        companyId: string | null;
        contactName?: string | null;
        companyName?: string | null;
        value: {
          amountMinor: string;
          currency: string;
        };
        exchangeRate: number | null;
        baseAmountMinor: string | null;
        /** @enum {string} */
        status: 'open' | 'won' | 'lost';
        closedAt: string | null;
        expectedCloseDate: string | null;
        ownerUserId: string | null;
        createdByUserId?: string | null;
        updatedByUserId?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
      };
    };
    CreateDealDto: {
      title: string;
      /** Format: uuid */
      contactId?: string | null;
      /** Format: uuid */
      companyId?: string | null;
      /** Format: uuid */
      pipelineId?: string | null;
      /** Format: uuid */
      stageId?: string | null;
      value: {
        amountMinor: string;
        currency: string;
      };
      /** Format: date-time */
      expectedCloseDate?: string | null;
      /** Format: uuid */
      ownerUserId?: string | null;
    };
    MoveDealStageDto: {
      /** Format: uuid */
      toStageId: string;
      lostReasonCode?: string | null;
    };
    CloseDealDto: {
      /** @enum {string} */
      outcome: 'won' | 'lost';
      lostReasonCode?: string | null;
    };
    ActivityListEnvelopeResponse: {
      data: {
        items: {
          id: string;
          /** @enum {string} */
          type: 'call' | 'meeting' | 'task' | 'email';
          subject: string;
          dueAt: string | null;
          completedAt: string | null;
          relatedType: string | null;
          relatedId: string | null;
          assignedToUserId: string | null;
          relatedName?: string | null;
          dealStageId?: string | null;
          dealStageNameI18n?: {
            [key: string]: string;
          } | null;
          createdByUserId?: string | null;
          updatedByUserId?: string | null;
          createdAt?: string | null;
          updatedAt?: string | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
      };
    };
    CreateActivityDto: {
      /** @enum {string} */
      type: 'call' | 'meeting' | 'task' | 'email';
      subject: string;
      /** Format: date-time */
      dueAt?: string | null;
      /** @enum {string|null} */
      relatedType?: 'contact' | 'company' | 'deal' | null;
      /** Format: uuid */
      relatedId?: string | null;
      /** Format: uuid */
      assignedToUserId?: string | null;
    };
    ActivityEnvelopeResponse: {
      data: {
        id: string;
        /** @enum {string} */
        type: 'call' | 'meeting' | 'task' | 'email';
        subject: string;
        dueAt: string | null;
        completedAt: string | null;
        relatedType: string | null;
        relatedId: string | null;
        assignedToUserId: string | null;
        relatedName?: string | null;
        dealStageId?: string | null;
        dealStageNameI18n?: {
          [key: string]: string;
        } | null;
        createdByUserId?: string | null;
        updatedByUserId?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
      };
    };
    UpdateActivityDto: {
      /** @enum {string} */
      type?: 'call' | 'meeting' | 'task' | 'email';
      subject?: string;
      /** Format: date-time */
      dueAt?: string | null;
      /** Format: uuid */
      assignedToUserId?: string | null;
    };
    CreateNoteDto: {
      body: string;
      /** @enum {string} */
      relatedType: 'contact' | 'company' | 'deal' | 'activity';
      /** Format: uuid */
      relatedId: string;
    };
    NoteEnvelopeResponse: {
      data: {
        id: string;
        body: string;
        relatedType: string;
        relatedId: string;
        createdAt: string;
        updatedAt: string;
        createdByUserId: string | null;
        createdByName: string | null;
      };
    };
    NoteListEnvelopeResponse: {
      data: {
        items: {
          id: string;
          body: string;
          relatedType: string;
          relatedId: string;
          createdAt: string;
          updatedAt: string;
          createdByUserId: string | null;
          createdByName: string | null;
        }[];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  OrganizationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOrganizationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationEnvelopeResponse'];
        };
      };
    };
  };
  OrganizationsController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationDetailResponse'];
        };
      };
    };
  };
  OrganizationsController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationDeleteResponse'];
        };
      };
    };
  };
  OrganizationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOrganizationDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationEnvelopeResponse'];
        };
      };
    };
  };
  OrganizationsController_getCurrent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationDetailResponse'];
        };
      };
    };
  };
  OrganizationsController_cancelDeletion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationEnvelopeResponse'];
        };
      };
    };
  };
  OrganizationsController_getSettings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsEnvelopeResponse'];
        };
      };
    };
  };
  OrganizationsController_updateSettings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOrganizationSettingsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsUpdateEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_listMyOrganizations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MyOrganizationsEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_listMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembersEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_listInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitationsEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_invite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteUserDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitationCreatedEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_acceptInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembershipMessageEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberRoleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembershipMessageEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_removeMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembershipMessageEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_revokeInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembershipMessageEnvelopeResponse'];
        };
      };
    };
  };
  MembershipsController_switchOrg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SwitchOrgDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SwitchOrgEnvelopeResponse'];
        };
      };
    };
  };
  AuthController_signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthMessageEnvelopeResponse'];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header: {
        'user-agent': string;
        'x-forwarded-for': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthEnvelopeResponse'];
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPairEnvelopeResponse'];
        };
      };
    };
  };
  AuthController_requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestPasswordResetDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthMessageEnvelopeResponse'];
        };
      };
    };
  };
  AuthController_completePasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompletePasswordResetDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthMessageEnvelopeResponse'];
        };
      };
    };
  };
  UsersController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileEnvelopeResponse'];
        };
      };
    };
  };
  UsersController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileEnvelopeResponse'];
        };
      };
    };
  };
  UsersController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMessageEnvelopeResponse'];
        };
      };
    };
  };
  UsersController_listSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionsEnvelopeResponse'];
        };
      };
    };
  };
  UsersController_revokeSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMessageEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_listRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RolesEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_createRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRoleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleCreatedEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_getRoleMatrix: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleMatrixEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_deleteRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleMessageEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRoleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleMessageEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_assignRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignRoleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleMessageEnvelopeResponse'];
        };
      };
    };
  };
  RolesController_transferOwnership: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferOwnershipDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleMessageEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_getBilling: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BillingEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_createSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSubscriptionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionCreatedEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_enableTrial: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnableModuleTrialDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BillingMessageEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_disableModule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BillingDisableModuleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BillingMessageEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_reconcile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReconcileEnvelopeResponse'];
        };
      };
    };
  };
  BillingController_handleWebhook: {
    parameters: {
      query?: never;
      header: {
        'stripe-signature': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WebhookResponse'];
        };
      };
    };
  };
  ModuleRegistryController_listModules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModuleCatalogEnvelopeResponse'];
        };
      };
    };
  };
  ModuleRegistryController_getNavigation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NavigationEnvelopeResponse'];
        };
      };
    };
  };
  ModuleRegistryController_getDashboardWidgets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardWidgetsEnvelopeResponse'];
        };
      };
    };
  };
  ModuleRegistryController_enableModule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnableModuleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModuleRegistryMessageEnvelopeResponse'];
        };
      };
    };
  };
  ModuleRegistryController_disableModule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DisableModuleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModuleRegistryMessageEnvelopeResponse'];
        };
      };
    };
  };
  AuditLogController_queryAuditLog: {
    parameters: {
      query: {
        actorUserId: string;
        entityType: string;
        entityId: string;
        action: string;
        fromDate: string;
        toDate: string;
        page: string;
        pageSize: string;
      };
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditLogQueryEnvelopeResponse'];
        };
      };
    };
  };
  SearchController_search: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchEnvelopeResponse'];
        };
      };
    };
  };
  FxRatesController_listCurrencies: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrenciesEnvelopeResponse'];
        };
      };
    };
  };
  FxRatesController_getRatesForBase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        baseCurrency: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FxRatesEnvelopeResponse'];
        };
      };
    };
  };
  FxRatesController_getRate: {
    parameters: {
      query: {
        date: string;
      };
      header?: never;
      path: {
        baseCurrency: string;
        quoteCurrency: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FxRateEnvelopeResponse'];
        };
      };
    };
  };
  FxRatesController_triggerSnapshot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FxSnapshotEnvelopeResponse'];
        };
      };
    };
  };
  ContactsController_list: {
    parameters: {
      query: {
        search: string;
        companyId: string;
        page: string;
        pageSize: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContactListEnvelopeResponse'];
        };
      };
    };
  };
  ContactsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateContactDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContactEnvelopeResponse'];
        };
      };
    };
  };
  ContactsController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContactEnvelopeResponse'];
        };
      };
    };
  };
  ContactsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateContactDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContactEnvelopeResponse'];
        };
      };
    };
  };
  ContactsController_merge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MergeContactsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MergeEnvelopeResponse'];
        };
      };
    };
  };
  CompaniesController_list: {
    parameters: {
      query: {
        search: string;
        page: string;
        pageSize: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyListEnvelopeResponse'];
        };
      };
    };
  };
  CompaniesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCompanyDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyEnvelopeResponse'];
        };
      };
    };
  };
  CompaniesController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyEnvelopeResponse'];
        };
      };
    };
  };
  CompaniesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCompanyDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompanyEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_list: {
    parameters: {
      query: {
        search: string;
        stageId: string;
        status: string;
        fromDate: string;
        toDate: string;
        sortBy: string;
        sortDir: string;
        page: string;
        pageSize: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealListEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDealDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_moveStage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveDealStageDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_close: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CloseDealDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealEnvelopeResponse'];
        };
      };
    };
  };
  DealsController_reopen: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DealEnvelopeResponse'];
        };
      };
    };
  };
  ActivitiesController_list: {
    parameters: {
      query: {
        search: string;
        fromDate: string;
        toDate: string;
        assigneeUserId: string;
        unassigned: string;
        completed: string;
        page: string;
        pageSize: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityListEnvelopeResponse'];
        };
      };
    };
  };
  ActivitiesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateActivityDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityEnvelopeResponse'];
        };
      };
    };
  };
  ActivitiesController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityEnvelopeResponse'];
        };
      };
    };
  };
  ActivitiesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateActivityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityEnvelopeResponse'];
        };
      };
    };
  };
  ActivitiesController_complete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityEnvelopeResponse'];
        };
      };
    };
  };
  PipelinesController_getDefault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNoteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NoteEnvelopeResponse'];
        };
      };
    };
  };
  NotesController_listByRelated: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        relatedType: string;
        relatedId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NoteListEnvelopeResponse'];
        };
      };
    };
  };
}
