export {
  createContactSchema,
  updateContactSchema,
  mergeContactsSchema,
  createDealSchema,
  moveDealStageSchema,
  closeDealSchema,
  createActivitySchema,
  CreateContactDto,
  UpdateContactDto,
  MergeContactsDto,
  CreateDealDto,
  MoveDealStageDto,
  CloseDealDto,
  CreateActivityDto,
  ContactResponse,
  DealResponse,
  ActivityResponse,
  ContactEnvelopeResponse,
  MergeEnvelopeResponse,
  DealEnvelopeResponse,
  ActivityEnvelopeResponse,
} from './crm.dto.js';
